IF OBJECT_ID('SimCalculation', 'FN') IS NOT NULL
DROP FUNCTION SimCalculation;
IF OBJECT_ID('MaximalDistance', 'FN') IS NOT NULL
DROP FUNCTION MaximalDistance;
IF OBJECT_ID('Similarity', 'U') IS NOT NULL
DROP TABLE Similarity;
IF OBJECT_ID('MediaItems', 'U') IS NOT NULL
DROP TABLE MediaItems;

-- Create the MediaItems table
CREATE TABLE MediaItems (
MID NUMERIC(11,0) PRIMARY KEY,
PROD_YEAR NUMERIC(4,0),
TITLE NVARCHAR(100)
);

-- Create the Similarity table
CREATE TABLE Similarity(
MID1 NUMERIC(11,0) NOT NULL,
MID2 NUMERIC(11,0) NOT NULL,
PRIMARY KEY (MID1,MID2),
FOREIGN KEY (MID1) REFERENCES MediaItems(MID),
FOREIGN KEY (MID2) REFERENCES MediaItems(MID),
SIMILARITY REAL
);

GO
-- Create the MaximalDistance function
CREATE FUNCTION MaximalDistance()
RETURNS SMALLINT
AS
BEGIN
DECLARE @PROD_YEARa NUMERIC(4,0), @PROD_YEARb NUMERIC(4,0);
SELECT @PROD_YEARa = MAX(PROD_YEAR), @PROD_YEARb = MIN(PROD_YEAR) FROM MediaItems;
DECLARE @result SMALLINT = ABS(@PROD_YEARa - @PROD_YEARb);
RETURN @result;
END;

-- Create the SimCalculation function
GO
CREATE FUNCTION SimCalculation(@MID1 NUMERIC(11,0), @MID2 NUMERIC(11,0), @maximal_distance SMALLINT)
RETURNS REAL
AS
BEGIN
DECLARE @PROD_YEARA NUMERIC(4,0),@PROD_YEARB NUMERIC(4,0);
SELECT @PROD_YEARA= PROD_YEAR FROM MediaItems WHERE MID=@MID1;
SELECT @PROD_YEARB= PROD_YEAR FROM MediaItems WHERE MID=@MID2;
DECLARE @distance SMALLINT = ABS(@PROD_YEARA - @PROD_YEARB);
DECLARE @result REAL = 1 - (@distance / @maximal_distance);
RETURN @result;
END;